// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNVG0y6gIVGut324Dgi4sRlq-W0an9nig',
    appId: '1:646611315356:android:deeb701f161218f9041b59',
    messagingSenderId: '646611315356',
    projectId: 'fcmauthcation',
    storageBucket: 'fcmauthcation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY-tL6lB_DNgxNnPEq6FzW9tGP8Zbugec',
    appId: '1:646611315356:ios:7a2eb1870f767da0041b59',
    messagingSenderId: '646611315356',
    projectId: 'fcmauthcation',
    storageBucket: 'fcmauthcation.appspot.com',
    androidClientId: '646611315356-usm28s62gf34r09i4uoapsq53epnelsh.apps.googleusercontent.com',
    iosClientId: '646611315356-im2mt47ug2g9rtef28pf3j5ad3921q2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.userFierAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY-tL6lB_DNgxNnPEq6FzW9tGP8Zbugec',
    appId: '1:646611315356:ios:7a2eb1870f767da0041b59',
    messagingSenderId: '646611315356',
    projectId: 'fcmauthcation',
    storageBucket: 'fcmauthcation.appspot.com',
    androidClientId: '646611315356-usm28s62gf34r09i4uoapsq53epnelsh.apps.googleusercontent.com',
    iosClientId: '646611315356-im2mt47ug2g9rtef28pf3j5ad3921q2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.userFierAuth',
  );
}
